//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Instant_Feedback_UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceListDetail
    {
        public int PriceListDetailId { get; set; }
        public int SiteId { get; set; }
        public int PriceListId { get; set; }
        public int ItemId { get; set; }
        public int MeasuringUnitId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> StkMaxBasePrice { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<int> ParentItemId { get; set; }
        public Nullable<int> UserId { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public Nullable<byte> Inactive { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> PriceWithVAT { get; set; }
        public Nullable<int> VATId { get; set; }
        public Nullable<decimal> VATPercent { get; set; }
        public Nullable<decimal> Delta { get; set; }
        public Nullable<decimal> AddPercent { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public Nullable<decimal> MaxPrice { get; set; }
        public Nullable<decimal> MinPriceWithVAT { get; set; }
        public Nullable<decimal> MaxPriceWithVAT { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public bool IsFocus { get; set; }
    }
}
